# File: simple-param.yml
parameters:
  - name: yesNo # name of the parameter; required
    type: boolean # data type of the parameter; required
    default: false

steps:
  - script: echo ${{ parameters.yesNo }}
  